# Sorting

In [5]:
import time
import numpy as np
np.random.seed(0)

In [6]:
data = np.random.randint(1,10000,17000)

# Insertion sort

In [7]:
def insertion_sort(array):
    start = time.time()
    #Implement Insertion Sort
    for i in range(1, len(array)):
        # Assign the current element to a variable 'key_item'
        key_item = array[i]
        # Set up a variable 'j' to keep track of the position in the sorted portion of the array
        j = i - 1
        # While 'j' is not less than zero and 'key_item' is less than the element at position 'j'
        while j >= 0 and key_item < array[j]:
            # Shift the element at position 'j' one position to the right
            array[j + 1] = array[j]
            # Decrement 'j' to move left one position in the sorted portion
            j -= 1
        # Insert 'key_item' into the correct position in the sorted portion
        array[j + 1] = key_item
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(array))
    return array
    

In [8]:
arr= insertion_sort(data)

The time of execution of above program is : 18394.965648651123 ms for a size of  17000


In [9]:
arr

array([   1,    1,    1, ..., 9999, 9999, 9999])

# Merge array first implementation

In [24]:
def merge(arr,left,right,mid):
    start = time.time()
    #Auxiliar array
    new_arr = np.zeros(len(arr))
    i = left
    j = mid + 1
    k = left
    while i <= mid and j <= right:
        if arr[i] < arr[j]:
            new_arr[k] = arr[i]
            i += 1
        else:
            new_arr[k] = arr[j]
            j += 1
        k += 1

    while i <= mid:
        new_arr[k] = arr[i]
        i += 1
        k += 1

    while j <= right:
        new_arr[k] = arr[j]
        j += 1
        k += 1

    for i in range(left,right + 1):
        arr[i] = new_arr[i]
    
    end = time.time()
    #print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr


In [21]:
data = np.random.randint(1,10000,17000)
left = 0
right = len(data) - 1
mid = (left + right) // 2
arr= merge(arr,left,right,mid)


The time of execution of above program is : 5.092859268188477 ms for a size of  17000


# Merge with division

In [22]:
def merge_sort(arr,left,right):
    if left < right:
        mid = (left + right) // 2
        merge_sort(arr,left,mid)
        merge_sort(arr,mid + 1,right)
        merge(arr,left,right,mid)
    return arr


In [25]:
data = np.random.randint(1,10000,17000)
left = 0
right = len(data) - 1
print(data)
start = time.time()
arr= merge_sort(data,left,right)
end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
print(arr)

[ 573 2302 5791 ... 9265 7091 9692]
The time of execution of above program is : 186.0675811767578 ms for a size of  17000
[   1    2    2 ... 9996 9996 9997]


### Algorithm of your choice: RadixSort

#### Complexity O (w*n)

In [1]:
# radix_sort(arr) takes an array 'arr' as input and returns a sorted version of it.
def radix_sort(arr):
    # Find the maximum element in the array 'arr'
    max_element = max(arr)
    # Calculate the number of digits in the maximum element
    num_digits = len(str(max_element))
    # Sort the array 'arr' based on the digits starting from the least significant digit to the most significant digit.
    for i in range(num_digits):
        arr = counting_sort_on_digit(arr, i)
    # Return the sorted array
    return arr

# counting_sort_on_digit(arr, digit) takes an array 'arr' and an integer 'digit' as input and returns a sorted version of the array based on the 'digit'-th place value.
def counting_sort_on_digit(arr, digit):
    # Find the length of the array 'arr'
    n = len(arr)
    # Create an output array with all elements set to 0
    output = [0] * n
    # Create a count array to store the frequency of each digit (0 to 9)
    count = [0] * 10
    # Count the frequency of each digit
    for i in range(n):
        index = get_digit(arr[i], digit)
        count[index] += 1
    # Accumulate the count array
    for i in range(1, 10):
        count[i] += count[i - 1]
    # Place the elements of the array 'arr' in their correct position in the 'output' array
    for i in range(n - 1, -1, -1):
        index = get_digit(arr[i], digit)
        output[count[index] - 1] = arr[i]
        count[index] -= 1
    # Return the sorted array 'output'
    return output

# get_digit(num, digit) takes an integer 'num' and an integer 'digit' as input and returns the 'digit'-th place value of the integer 'num'.
def get_digit(num, digit):
    # Return the 'digit'-th place value of the integer 'num'
    return (num // 10**digit) % 10



In [4]:
import time
import numpy as np
np.random.seed(0)
data= np.random.randint(1,10000,17000)

start = time.time()
arr=radix_sort(data)
end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))

The time of execution of above program is : 74.99933242797852 ms for a size of  17000


## Conclusion

It is very important to take into account the complexity of the algorithms when implementing them. This can make a code run for 1 year or 1 hour. It is always necessary to have a balance between software and hardware. First check that the algorithm is as optimal as possible in terms of code, then optimize the hardware if the code is too computationally heavy.